//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.Mobile.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.Mobile.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number in the encrypted data isn&apos;t correct..
        /// </summary>
        internal static string BlockVersionMismatch {
            get {
                return ResourceManager.GetString("BlockVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration system failed to initialize.
        /// </summary>
        internal static string ConfigurationFailure {
            get {
                return ResourceManager.GetString("ConfigurationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplication section data found, and not allowed..
        /// </summary>
        internal static string DuplicationSectionData {
            get {
                return ResourceManager.GetString("DuplicationSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;EncryptedSection&gt; xml element is missing a name attributed..
        /// </summary>
        internal static string EncryptedMissingName {
            get {
                return ResourceManager.GetString("EncryptedMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte array value must not be empty..
        /// </summary>
        internal static string ExceptionByteArrayValueMustBeGreaterThanZeroBytes {
            get {
                return ResourceManager.GetString("ExceptionByteArrayValueMustBeGreaterThanZeroBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex string..
        /// </summary>
        internal static string InvalidHexString {
            get {
                return ResourceManager.GetString("InvalidHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a required attribute: &apos;{0}&apos;.
        /// </summary>
        internal static string MissingAttribute {
            get {
                return ResourceManager.GetString("MissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required element is missing: &apos;{0}&apos;..
        /// </summary>
        internal static string MissingElement {
            get {
                return ResourceManager.GetString("MissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section data is missing fo &apos;{0}&apos;. Unlike the desktop, this implementation requires that section data exists..
        /// </summary>
        internal static string MissingSectionData {
            get {
                return ResourceManager.GetString("MissingSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attribute &apos;{0}&apos; must have a value..
        /// </summary>
        internal static string RequiredAttributeEmpty {
            get {
                return ResourceManager.GetString("RequiredAttributeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be empty..
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the type: {0}.
        /// </summary>
        internal static string TypeLoadError {
            get {
                return ResourceManager.GetString("TypeLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized attribute &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedAttribute {
            get {
                return ResourceManager.GetString("UnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized element &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedElement {
            get {
                return ResourceManager.GetString("UnrecognizedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported property type exists..
        /// </summary>
        internal static string UnsupportedPropertyType {
            get {
                return ResourceManager.GetString("UnsupportedPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized value cannot be assigned to target property type {0}..
        /// </summary>
        internal static string WrongConvertedType {
            get {
                return ResourceManager.GetString("WrongConvertedType", resourceCulture);
            }
        }
    }
}
